# Generated by Django 3.1.1 on 2020-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('isAccepted', models.BooleanField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
